### ISSUE TITLE
Add wiki flavored blockquote

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-markdown#14]
Mike Caulfield suggests:

I would prefer to make a special fedwiki flavor in which an initial > would blockquote the whole markdown item. In other words, if the first character is the angle bracket wrap the whole item in blockquote and ignore subsequent angle brackets. If you want something outside blockquotes, make a new item. This is the simplest solution and it fits with the movable items philosophy of federated wiki.

See ongoing discussion in the wiki goals pod and elsewhere. [wiki](http://ward.asia.wiki.org/view/welcome-visitors/view/markdown-test/journal.hapgood.net/markdown-test)

**Comment by WardCunningham** [comment]
The phrase, "ignore subsequent" in Mike's suggestion implies some sort of processing beyond that of individual lines. Since the angle bracket survives the line at a time processing the blockquote transformation could be applied to the collection of lines before they are joined. [source](https://github.com/fedwiki/wiki-plugin-markdown/blob/74e69722d7d6372a1788c9252e663edc04a62e04/client/markdown.coffee#L55-L60)

We can expect that this is not the last such transformation to be introduced into wiki flavored markdown. An acceptable approach might be to construct a second pipeline of function applications that starts with output and ends with join.

```
  join blockquote output
```

This would replace the current join as the last line of expand.

**Comment by paul90** [comment]
Although in #17 support for markdown blockquotes is added, I can't help but wonder if it would be better to have a quote plugin.

**Comment by WardCunningham** [comment]
I could imagine SOURCE and AUTHOR markup which offers details only cluttering the page on hover or print. I wonder if some clever tooling would allow drag & drop quoting from random sites with proper attribution.
