### ISSUE TITLE
Consider adding back-tick code blocks

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-markdown#2]
When @nrn and I read through the github docs describing their flavor of markdown we both agreed that single `back-tick` for inline code blocks was a desirable and relevant feature. Github expands this with css for a little extra spacing front and back.

We don't suggest adding the `triple-back-tick` variant since we already have that with our Code plugin.

**Comment by san650** [comment]
I've implemented this functionality, I think having inline code blocks it's really useful when writing technical articles.

#7
