### ISSUE TITLE
External links do not have glyph indicating they are external

### ISSUE THREAD

**Issue by cgalo5758** [fedwiki/wiki-plugin-markdown#25]
When writing an external link with the paragraph plugin, a little glyph shows up to indicate that the link will take you off the site. You'd expect the same behavior from the markdown plugin, but it doesn't do it.

**Comment by WardCunningham** [comment]
You are referring to a behavior of wiki, not one of markdown.

Our version of markdown recognizes wiki markup for both internal and external links. Try using the wiki markup. I think you will like it better.
