### ISSUE TITLE
Break lines on newline

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-markdown#3]
Markdown is sensitive to newlines.
If you want lines that run on you have to run them on.
This paragraph has lots of line breaks.
The output should be similarly broken.

A blank line means a new paragraph.
- bullets can begin on any line
- a number of lines will be a list
  where newlines
  are ignored
  until a new bullet.
- like this one

It takes a blank line to break out of bullet text.
Have you got all that?

**Comment by paul90** [comment]
Should a blank line break the content into two plugins? What about list items/bullets?

**Comment by WardCunningham** [comment]
I had markdown in the back of my mind when I was generalizing the state logic in the TextEditor. I think it could be made to split on blank line instead of newline. The markdown plugin calls up the TextEditor and could configure what is most appropriate.

I'm thinking bullets without blank lines should be one markdown item. I remember someone making this point in an issue long ago. It might have been @almereyda. I couldn't find the discussion. There are times you want a tightly associated list that would stay together when dragged.

If we get split on blank line to work, it would work for bullet lists too. Spaced bullets would be spaced on the screen too and free to move anywhere in the story.

**Comment by WardCunningham** [comment]
I notice that github.com is not consistent in how they handle newlines when rendering markdown. When viewing ReadMe.md they flow past newlines. But when rendering comments (as above) they break on newline. I would think with our paragraph at a time orientation we would want to break as this issue suggests. Rendering a whole file might reasonably work differently.

**Comment by san650** [comment]
I would like to work on this issue.

I think I can work on it in two separated steps.

The first step would be to make the markdown plugin sensitive to newlines, I have a working version with this, I have to wrap it up before I create a PR. The idea is to add a `<br>` tag element to lines that don't end with `>` char or are blank lines.

The second step would be to modify the textEditor to allow plugins to _request_ a new instance of the plugin, this way, we could request a **new** markdown plugin instance from the markdown plugin... I have to think a bit what's the best approach to doing this. An idea is to fire an event from the textEditor plugin on every new line and listen to that event from the markdown plugin and on a blank line, request a new markdown plugin instance to the textEditor. What do you think?

I'm just starting to understand how everything works, so this could be the wrong approach... please, let me know

**Comment by WardCunningham** [comment]
This might take a few tries to get right. Just meeting a markdown spec (if you can find one) is only part of the goal. A second goal is to fit in well with all the other formatting plugins while not taking anything away from the simplicity of plain text as rendered with the Paragraph plugin.

@paul90 has suggested that we separate text entry semantics from internal representation. This is a powerful idea but plugins don't yet attempt that distinction. I favor smaller steps while taking everything Paul suggests very seriously.

I've been using Markdown as my preferred way to do section titles and that is about it. Our education technology folks take quotation and citation much more seriously so we'd like to help them out by borrowing more markup from Markdown. Mike Caulfield is authoring blog posts in wiki and then rendering them with his own blog-stile page rendering logic. Here is an example and a post where he explains why what he is doing seems important.

http://journal.hapgood.net/penalty-compression.html
http://hapgood.us/2015/05/05/the-oer-case-for-federated-wiki/

Notice that Mike is using block quotes which is not the same as code blocks.

> Human madness is oftentimes a cunning and most feline thing. When you think it fled, it may have but become transfigured into some still subtler form. ― Herman Melville, Moby-Dick

I think if one were to quote three paragraphs then they would want those three paragraphs to appear as one wiki item. I'm just guessing here. I've argued that quoting is an obsolete idea in the context of federated wiki.

http://forage.ward.fed.wiki.org/citations-obsolete.html

I encourage you to try something and then explain what you were thinking. I mention blockquote because it has some multi-line complexity. If something is controversial then there will be helpful discussion in the pull request.

**Comment by san650** [comment]
Thanks for your comments. I'll open a PR this week with some ideas I have for supporting the newlines and maybe block-quotes. We can then continue with the discussion on the PR.

**Comment by san650** [comment]
I've created a PR which adds a break element at the end of each line that doesn't end with a block element.

If you're ok with the PR, I think the next step would be to start working on the textEditor to allow plugins to configure _when_ to create a new paragraph. In the case of markdown plugin we would like to create a new paragraph when there's an empty line. 

What do you think? 

I know this doesn't address all issues (like creating a paragraph for lists or block-quotes) but it's a step closer to that.
