### ISSUE TITLE
Bold at start of line triggers bullets

### ISSUE THREAD

**Issue by michaelarthurcaulfield** [fedwiki/wiki-plugin-markdown#5]
Users should be able to use _emphasis_ markers at the beginning of a paragraph, like this:

_Emphasis text_ can be useful.
**Bold** can be useful too.

Currently that produces a bulleted list instead. May just be a case of rule precedence, or may be that bullets should require spaces between them and content.

**Comment by san650** [comment]
This is fixed in master. See 52cd8f2c4adae0bffbce7fb5d4d50d0de36c2462

**Comment by paul90** [comment]
This fix has been included in **\+ wiki-plugin-markdown@0.2.3**
